### ISSUE TITLE
Menu?

### ISSUE THREAD

**Issue by mrneilypops** [tomasdev/ghost-casper-plain#1]
Hi,
Could you include the navigation menu?

Regards,
Neil

**Comment by tomasdev** [comment]
@mrneilypops which menu are you referring to? the original Casper didn't have one designed, I think? (if you have a demo running the old ghost with menu I can surely copy it over)

**Comment by mrneilypops** [comment]
@tomasdev
Sure,
https://mrneilypops.io

**Comment by mrneilypops** [comment]
I just made a fresh test install of Ghost v0.11.11 on Heroku just to show the menu is default on Casper (v1)
https://mrneilypops-test.herokuapp.com/

It is populated by adding items to the navigation menu...

**Comment by tomasdev** [comment]
@mrneilypops it has now been updated to v1.1.7 of the Casper theme (https://github.com/TryGhost/Casper/tree/1b86190c4d21f60f19cac154a0bd106562a0dd0b)
