### ISSUE TITLE
v1.1.7 menu problem

### ISSUE THREAD

**Issue by mrneilypops** [tomasdev/ghost-casper-plain#2]
Hi,
I downloaded and activated the update.
Thanks for the update but the menu does not populate.
There is no menu action on clicking the button...just a link to https://mrneilypops.org/# (??)

**Comment by tomasdev** [comment]
@mrneilypops just updated the readme https://github.com/tomasdev/ghost-casper-plain/blob/master/README.md seems you're missing jQuery. 

I'm not sure as to why in the Casper theme v1.1.7 that jQuery dependency is missing as well.
